// המאגר העצום
const allSongs = [
    // שירים שהיו ברשימה שלך - תויגו כפסטיגל רק אם הם באמת משם!
    { title: "לעוף", artist: "הראל סקעת", year: 2004, isFestigal: true },
    { title: "נסיכת פופ", artist: "רוני דואני", year: 2004, isFestigal: true },
    { title: "הכוח שבמה", artist: "שירי מימון", year: 2005, isFestigal: true },
    { title: "איש הברק", artist: "רן דנקר", year: 2005, isFestigal: true },
    { title: "מטרה מספר אחת", artist: "אגם בוחבוט", year: 2022 }, // שיר רגיל
    { title: "לילה מטורף בפסטיגל", artist: "שיר הנושא", year: 2011, isFestigal: true },
    { title: "במקצב הלב", artist: "אליאנה תדהר", year: 2012, isFestigal: true },
    { title: "תעשו לנו כבוד", artist: "נועה קירל", year: 2017 }, // שיר רגיל
    { title: "טיקיטאס", artist: "נועה קירל", year: 2018 }, // שיר רגיל
    { title: "אל תתייג אותי", artist: "אגם בוחבוט ונועה קירל", year: 2019 }, // שיר רגיל
    { title: "כאן הכל התחיל", artist: "שיר הנושא", year: 2020, isFestigal: true },
    { title: "זה הזמן", artist: "אנה זק ומרגי", year: 2022 }, // שיר רגיל
    { title: "הדרך שלי", artist: "רן דנקר", year: 2004 }, // שיר רגיל
    { title: "חיוך של מלאך", artist: "הראל מויאל", year: 2004 }, // שיר רגיל
    { title: "זורו", artist: "הראל מויאל", year: 2004, isFestigal: true },
    { title: "שלום עם עצמי", artist: "אנה זק", year: 2021 }, // שיר רגיל
    { title: "השיר שלי", artist: "מוקי", year: 2010 }, // שיר רגיל
    { title: "חשמל באוויר", artist: "לי בירן", year: 2011, isFestigal: true },
    { title: "ממה את מפחדת", artist: "נועה קירל ומרגי", year: 2019 }, // שיר רגיל
    { title: "פסטיגל פנטזיה", artist: "שיר הנושא", year: 2006, isFestigal: true },
    { title: "סופרסטאר", artist: "רוני דואני", year: 2004 }, // שיר רגיל
    { title: "לא עוצרת", artist: "רוני דואני", year: 2005 }, // שיר רגיל
    
    // להיטים וישראלי (ללא שינוי)
    { title: "זוט עני", artist: "אלה לי", year: 2020 },
    { title: "שימי פס", artist: "עדן חסון ואלה לי", year: 2021 },
    { title: "קומסי קומסה", artist: "סטפן לגר", year: 2018 },
    { title: "מוגזם", artist: "עברי לידר", year: 2017 },
    { title: "שבט אחים ואחיות", artist: "עידן רייכל", year: 2019 },
    { title: "מסיבה בחיפה", artist: "איתי לוי ואיזי", year: 2016 },
    { title: "חלקת אלוהים", artist: "עידן עמדי", year: 2017 },
    { title: "כאב של לוחמים", artist: "עידן עמדי", year: 2010 },
    { title: "בלילה", artist: "הפרויקט של עידן רייכל", year: 2013 },
    { title: "ירושלים של זהב", artist: "שולי נתן", year: 1967 },
    { title: "לו יהי", artist: "נעמי שמר", year: 1973 },
    { title: "אני ואתה", artist: "אריק איינשטיין", year: 1971 },
    { title: "יו יה", artist: "כוורת", year: 1973 },
    { title: "שיר הרעות", artist: "להקת הנחל", year: 1969 },
    { title: "פראג", artist: "אריק איינשטיין", year: 1969 },
    { title: "מלכות החרמון", artist: "להקת פיקוד צפון", year: 1968 },
    { title: "זמר נוגה", artist: "החלונות הגבוהים", year: 1967 },
    { title: "בשמלה אדומה", artist: "להקת הנחל", year: 1968 },
    { title: "חורשת האקליפטוס", artist: "צוות הווי נחל", year: 1968 },
    { title: "עטור מצחך", artist: "אריק איינשטיין", year: 1977 },
    { title: "עין גדי", artist: "אריק איינשטיין", year: 1966 },
    { title: "המגפיים של ברוך", artist: "כוורת", year: 1973 },
    { title: "נתתי לה חיי", artist: "כוורת", year: 1974 },
    { title: "הילדה הכי יפה בגן", artist: "יהודית רביץ", year: 1978 },
    { title: "אדון שוקו", artist: "אריק איינשטיין", year: 1973 },
    { title: "חלומות", artist: "רוחמה רז", year: 1979 },
    { title: "שיר אהבה בדואי", artist: "דויד ברוזה", year: 1978 },
    { title: "הללויה", artist: "גלי עטרי וחלב ודבש", year: 1979 },
    { title: "מחכים למשיח", artist: "שלום חנוך", year: 1985 },
    { title: "אהובתי", artist: "משינה", year: 1988 },
    { title: "אין לי ארץ אחרת", artist: "גלי עטרי", year: 1986 },
    { title: "שלל שרב", artist: "גידי גוב", year: 1985 },
    { title: "בואי נגיד שאני שלך", artist: "אלון אולארצ'יק", year: 1985 },
    { title: "בדד", artist: "זוהר ארגוב", year: 1988 },
    { title: "הכל עומד במקום", artist: "גלי עטרי", year: 1988 },
    { title: "רכבת לילה", artist: "משינה", year: 1986 },
    { title: "הפרח בגני", artist: "זוהר ארגוב", year: 1982 },
    { title: "רואים רחוק רואים שקוף", artist: "שמוליק קראוס", year: 1983 },
    { title: "עכשיו מעונן", artist: "אביב גפן", year: 1993 },
    { title: "למאיה יש אקדח", artist: "כנסיית השכל", year: 1993 },
    { title: "ככה זה", artist: "ברי סחרוף", year: 1998 },
    { title: "דיווה", artist: "דנה אינטרנשיונל", year: 1998 },
    { title: "ירח", artist: "שלמה ארצי", year: 1992 },
    { title: "אהבה קצרה", artist: "מאיר בנאי", year: 1992 },
    { title: "קח אותי", artist: "היהודים", year: 1995 },
    { title: "השיר שלנו", artist: "אביב גפן", year: 1998 },
    { title: "ג'סיקה", artist: "אתניקס", year: 1993 },
    { title: "התחנה הישנה", artist: "טיפקס", year: 1995 },
    { title: "צאי אל החלון", artist: "אייל גולן", year: 1997 },
    { title: "יפה שלי", artist: "אייל גולן", year: 1998 },
    { title: "מכופף הבננות", artist: "שבק ס", year: 1995 },
    { title: "איזה עולם", artist: "טיפקס", year: 1999 },
    { title: "תותים", artist: "אתניקס", year: 1992 },
    { title: "לבכות לך", artist: "אביב גפן", year: 1996 },
    { title: "דמעות", artist: "אייל גולן", year: 1998 },
    { title: "תתארו לכם", artist: "שלמה ארצי", year: 2007 },
    { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2005 },
    { title: "אם תלך", artist: "הפרויקט של עידן רייכל", year: 2003 },
    { title: "בואי", artist: "הפרויקט של עידן רייכל", year: 2002 },
    { title: "אנצל", artist: "מוש בן ארי", year: 2006 },
    { title: "סיגפו", artist: "בית הבובות", year: 2005 },
    { title: "ואת", artist: "הראל סקעת", year: 2006 },
    { title: "השקט שנשאר", artist: "שירי מימון", year: 2005 },
    { title: "יאללה לך הביתה מוטי", artist: "שרית חדד", year: 2001 },
    { title: "בחום של תל אביב", artist: "שרית חדד", year: 2004 },
    { title: "יומן מסע", artist: "אביב גפן", year: 2000 },
    { title: "משא ומתן", artist: "מוש בן ארי", year: 2006 },
    { title: "שירת הסטיקר", artist: "הדג נחש", year: 2004 },
    { title: "ניצחת איתי הכל", artist: "עמיר בניון", year: 2004 },
    { title: "ריקוד רומנטי", artist: "ישי לוי", year: 2008 },
    { title: "יסמין", artist: "הפיל הכחול", year: 2009 },
    { title: "עץ ירוק מפלסטיק", artist: "מרגלית צנעני", year: 2009 },
    { title: "ספרי לי", artist: "עומר אדם", year: 2011 },
    { title: "נמס ממך", artist: "עומר אדם", year: 2010 },
    { title: "תגידו לה", artist: "דודו אהרון", year: 2010 },
    { title: "תל אביב", artist: "עומר אדם", year: 2013 },
    { title: "מודה אני", artist: "עומר אדם", year: 2015 },
    { title: "שגרה מפוארת", artist: "עומר אדם", year: 2017 },
    { title: "מים שקופים", artist: "עומר אדם", year: 2019 },
    { title: "חורף באוטו", artist: "עומר אדם", year: 2021 },
    { title: "מתוק כשמרלי", artist: "אליעד", year: 2015 },
    { title: "ברבי", artist: "סטטיק ובן אל תבורי", year: 2015 },
    { title: "סלסולים", artist: "סטטיק ובן אל תבורי", year: 2016 },
    { title: "כביש החוף", artist: "סטטיק ובן אל תבורי", year: 2016 },
    { title: "יאסו", artist: "סטטיק ובן אל תבורי", year: 2019 },
    { title: "אפס מאמץ", artist: "סטטיק ובן אל ונטע", year: 2021 },
    { title: "גם זה יעבור", artist: "טונה", year: 2015 },
    { title: "סהרה", artist: "טונה", year: 2021 },
    { title: "כפרה שלי", artist: "רביד פלוטניק", year: 2017 },
    { title: "ויקיפדיה", artist: "חנן בן ארי", year: 2017 },
    { title: "אלוף העולם", artist: "חנן בן ארי", year: 2019 },
    { title: "שבורי לב", artist: "חנן בן ארי", year: 2019 },
    { title: "אמן על הילדים", artist: "חנן בן ארי", year: 2020 },
    { title: "עטלף עיוור", artist: "חנן בן ארי", year: 2023 },
    { title: "Toy", artist: "נטע ברזילי", year: 2018 },
    { title: "שני משוגעים", artist: "עומר אדם", year: 2018 },
    { title: "דרך השלום", artist: "פאר טסי", year: 2014 },
    { title: "אהבה חולה", artist: "פאר טסי", year: 2022 },
    { title: "רוז", artist: "פאר טסי", year: 2024 },
    { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2015 },
    { title: "מועבט", artist: "עדן בן זקן", year: 2021 },
    { title: "חיפשתי אותו בנרות", artist: "עדן בן זקן", year: 2023 },
    { title: "שקיעות אדומות", artist: "עדן חסון", year: 2020 },
    { title: "סיבובים", artist: "עדן חסון", year: 2020 },
    { title: "לאהוב אותך כל יום", artist: "עדן חסון", year: 2022 },
    { title: "פאוץ'", artist: "נועה קירל", year: 2019 },
    { title: "יהלומים", artist: "נועה קירל", year: 2021 },
    { title: "טרילילי טרללה", artist: "נועה קירל ואילן פלד", year: 2021 },
    { title: "פעמון", artist: "נועה קירל", year: 2022 },
    { title: "פנתרה", artist: "נועה קירל", year: 2022 },
    { title: "לך לישון", artist: "אנה זק", year: 2022 },
    { title: "מי זאת", artist: "אנה זק", year: 2022 },
    { title: "קופידון", artist: "אגם בוחבוט", year: 2022 },
    { title: "דובשנייה", artist: "שחר סאול, אגם בוחבוט ונורוז", year: 2022 },
    { title: "מסיבה", artist: "יסמין מועלם", year: 2020 },
    { title: "מחילה", artist: "יסמין מועלם", year: 2021 },
    { title: "אנג'ל", artist: "מרגי", year: 2021 },
    { title: "לא יוצא מסיבה", artist: "מרגי", year: 2021 },
    { title: "סתלבט בקיבוץ", artist: "פול טראנק", year: 2022 },
    { title: "תיק קטן", artist: "נס וסטילה", year: 2023 },
    { title: "חרבו דרבו", artist: "נס וסטילה", year: 2023 },
    { title: "קרן שמש", artist: "בניה ברבי", year: 2022 },

    // === קלאסיקות לועזיות (60s-80s) ===
    { title: "Hey Jude", artist: "The Beatles", year: 1968 },
    { title: "Yesterday", artist: "The Beatles", year: 1965 },
    { title: "Let It Be", artist: "The Beatles", year: 1970 },
    { title: "Paint It, Black", artist: "The Rolling Stones", year: 1966 },
    { title: "Respect", artist: "Aretha Franklin", year: 1967 },
    { title: "My Way", artist: "Frank Sinatra", year: 1969 },
    { title: "Rocket Man", artist: "Elton John", year: 1972 },
    { title: "Piano Man", artist: "Billy Joel", year: 1973 },
    { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
    { title: "Hotel California", artist: "Eagles", year: 1976 },
    { title: "Dancing Queen", artist: "ABBA", year: 1976 },
    { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
    { title: "Don't Stop Me Now", artist: "Queen", year: 1979 },
    { title: "Back In Black", artist: "AC/DC", year: 1980 },
    { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
    { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
    { title: "Take On Me", artist: "a-ha", year: 1985 },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
    { title: "Like a Prayer", artist: "Madonna", year: 1989 },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
    { title: "Wake Me Up Before You Go-Go", artist: "Wham!", year: 1984 },
    { title: "Careless Whisper", artist: "George Michael", year: 1984 },
    { title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
    { title: "Africa", artist: "Toto", year: 1982 },

    // === שנות ה-90 וה-2000 לועזי ===
    { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
    { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
    { title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
    { title: "Wannabe", artist: "Spice Girls", year: 1996 },
    { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
    { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
    { title: "Wonderwall", artist: "Oasis", year: 1995 },
    { title: "No Scrubs", artist: "TLC", year: 1999 },
    { title: "Ms. Jackson", artist: "Outkast", year: 2000 },
    { title: "In the End", artist: "Linkin Park", year: 2001 },
    { title: "Without Me", artist: "Eminem", year: 2002 },
    { title: "Lose Yourself", artist: "Eminem", year: 2002 },
    { title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
    { title: "Bring Me To Life", artist: "Evanescence", year: 2003 },
    { title: "Toxic", artist: "Britney Spears", year: 2003 },
    { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
    { title: "Don't Stop The Music", artist: "Rihanna", year: 2007 },
    { title: "Umbrella", artist: "Rihanna", year: 2007 },
    { title: "I Kissed A Girl", artist: "Katy Perry", year: 2008 },
    { title: "Love Story", artist: "Taylor Swift", year: 2008 },
    { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
    { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009 },

    // === שנות ה-2010 וה-2020 לועזי ===
    { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
    { title: "Someone Like You", artist: "Adele", year: 2011 },
    { title: "Hello", artist: "Adele", year: 2015 },
    { title: "Counting Stars", artist: "OneRepublic", year: 2013 },
    { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
    { title: "Believer", artist: "Imagine Dragons", year: 2017 },
    { title: "Wake Me Up", artist: "Avicii", year: 2013 },
    { title: "Happy", artist: "Pharrell Williams", year: 2013 },
    { title: "Uptown Funk", artist: "Bruno Mars", year: 2014 },
    { title: "Chandelier", artist: "Sia", year: 2014 },
    { title: "Sorry", artist: "Justin Bieber", year: 2015 },
    { title: "Peaches", artist: "Justin Bieber", year: 2021 },
    { title: "STAY", artist: "The Kid LAROI", year: 2021 },
    { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
    { title: "Despacito", artist: "Luis Fonsi", year: 2017 },
    { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
    { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
    { title: "Save Your Tears", artist: "The Weeknd", year: 2020 },
    { title: "7 rings", artist: "Ariana Grande", year: 2019 },
    { title: "bad guy", artist: "Billie Eilish", year: 2019 },
    { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
    { title: "As It Was", artist: "Harry Styles", year: 2022 },
    { title: "Levitating", artist: "Dua Lipa", year: 2020 },
    { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
    { title: "vampire", artist: "Olivia Rodrigo", year: 2023 },
    { title: "Espresso", artist: "Sabrina Carpenter", year: 2024 },
    
    // ================================================================
    // === שירי פסטיגל מקוריים שהוספו למאגר (שירים שיצאו במיוחד למופע) ===
    // ================================================================
    { title: "כמו רובין הוד", artist: "רן דנקר", year: 2004, isFestigal: true },
    { title: "האהבה מנצחת", artist: "יעל בר זוהר", year: 2004, isFestigal: true },
    { title: "שלוש חברות", artist: "דנה פרידר, ימית סול ואלונה טל", year: 2007, isFestigal: true },
    { title: "נערה חשמלית", artist: "דנה פרידר", year: 2007, isFestigal: true },
    { title: "צונאמי", artist: "עדי הימלבלוי", year: 2008, isFestigal: true },
    { title: "שיר אהבה צרפתי", artist: "עמית פרקש", year: 2007, isFestigal: true },
    { title: "החיצים של האהבה", artist: "רוני דואני", year: 2006, isFestigal: true },
    { title: "מלכה קרה", artist: "לירז צ'רכי", year: 2006, isFestigal: true },
    { title: "הפנתר", artist: "יהודה לוי", year: 2003, isFestigal: true },
    { title: "מטרה מספר אחת", artist: "עדי הימלבלוי ואגם רודברג", year: 2009, isFestigal: true }, // המקורית מהפסטיגל!
    { title: "ילדים של העתיד", artist: "אליאנה תדהר ותובל שפיר", year: 2011, isFestigal: true },
    { title: "אין גבולות", artist: "סאבלימינל והצל", year: 2003, isFestigal: true },
    { title: "יד ביד", artist: "משתתפי הפסטיגל", year: 2004, isFestigal: true },
    { title: "החיים הם פסטיגל", artist: "משתתפי הפסטיגל", year: 2005, isFestigal: true },
    { title: "פסטיגל על הזמן", artist: "משתתפי הפסטיגל", year: 2007, isFestigal: true },
    { title: "תפוס ת'פסטיגל", artist: "משתתפי הפסטיגל", year: 2008, isFestigal: true },
    { title: "קונג פו פסטיגל", artist: "משתתפי הפסטיגל", year: 2009, isFestigal: true },
    { title: "אני פסטיגל", artist: "משתתפי הפסטיגל", year: 2012, isFestigal: true },
    { title: "X פסטיגל", artist: "משתתפי הפסטיגל", year: 2013, isFestigal: true },
    { title: "משחקי הפסטיגל", artist: "משתתפי הפסטיגל", year: 2014, isFestigal: true },
    { title: "היי סקול פסטיגל", artist: "משתתפי הפסטיגל", year: 2015, isFestigal: true },
    { title: "סטורי של פסטיגל", artist: "משתתפי הפסטיגל", year: 2017, isFestigal: true },
    { title: "Freestyle פסטיגל", artist: "משתתפי הפסטיגל", year: 2018, isFestigal: true },
    { title: "Play פסטיגל", artist: "משתתפי הפסטיגל", year: 2019, isFestigal: true },
    { title: "Sky High פסטיגל", artist: "משתתפי הפסטיגל", year: 2021, isFestigal: true },
    { title: "סינג פסטיגל", artist: "משתתפי הפסטיגל", year: 2023, isFestigal: true },
    { title: "חברים בכל מיני צבעים", artist: "שרית חדד", year: 1998, isFestigal: true },
    { title: "שיר הנועמי", artist: "נועם קניאל", year: 1980, isFestigal: true }
];